# Generated by Django 5.1.3 on 2024-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
